---
# Copyright (C) 2026 Patryk Ściborek <patryk@sciborek.com>
# Copyright (C) 2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

collections: ['debops.debops']

dependencies: []

galaxy_info:

  author: 'Patryk Ściborek'
  description: 'Manage Docker container services with nginx reverse proxy'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.11.0'

  platforms:

    - name: 'Ubuntu'
      versions: ['all']

    - name: 'Debian'
      versions: ['all']

  galaxy_tags:
    - docker
    - containers
    - nginx
    - proxy
