---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2021      Julien Lecomte <julien@lecomte.at>
# Copyright (C) 2021-2022 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2021-2022 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Import custom Ansible plugins
  ansible.builtin.import_role:
    name: 'ansible_plugins'

- name: Import DebOps global handlers
  ansible.builtin.import_role:
    name: 'global_handlers'

- name: Import DebOps secret role
  ansible.builtin.import_role:
    name: 'secret'

# Package installation [[[1
- name: Install Zabbix agent packages
  ansible.builtin.apt:
    name: '{{ (zabbix_agent__base_packages
             + zabbix_agent__packages) | flatten }}'
    state: '{{ zabbix_agent__deploy_state }}'
    purge: True
  register: zabbix_agent__register_packages
  until: zabbix_agent__register_packages is succeeded

- name: Add Zabbix UNIX account to required groups
  ansible.builtin.user:
    name: '{{ zabbix_agent__user }}'
    groups: '{{ zabbix_agent__combined_additional_groups | join(",") }}'
    state: 'present'
    append: True
  notify: [ 'Check zabbix-agent and restart', 'Check zabbix-agent2 and restart' ]
  when: zabbix_agent__deploy_state != 'absent'

- name: Divert Zabbix agent configuration file
  debops.debops.dpkg_divert:
    path: '{{ zabbix_agent__conf_file_path }}'
    state: 'present'
  notify: [ 'Check zabbix-agent and restart', 'Check zabbix-agent2 and restart' ]
  when: zabbix_agent__deploy_state != 'absent'

# Zabbix agent configuration [[[1
- name: Generate Zabbix agent configuration file
  ansible.builtin.template:
    src: 'etc/zabbix/zabbix_agentd.conf.j2'
    dest: '{{ zabbix_agent__conf_file_path }}'
    owner: 'root'
    group: '{{ zabbix_agent__group }}'
    mode: '0640'
    unsafe_writes: '{{ True if (core__unsafe_writes | d(ansible_local.core.unsafe_writes | d()) | bool) else omit }}'
  notify: [ 'Check zabbix-agent and restart', 'Check zabbix-agent2 and restart' ]
  when: zabbix_agent__deploy_state != 'absent'

- name: Install secret key
  ansible.builtin.copy:
    content: '{{ zabbix_agent__tls_psk_secret }}'
    dest: '/etc/zabbix/secret.key'
    owner: 'root'
    group: '{{ zabbix_agent__group }}'
    mode: '0640'
  no_log: '{{ debops__no_log | d(True) }}'
  notify: [ 'Check zabbix-agent and restart', 'Check zabbix-agent2 and restart' ]
  when: zabbix_agent__deploy_state != 'absent' and
        zabbix_agent__tls_mode == 'psk'

- name: Remove unused PSK secret key
  ansible.builtin.file:
    path: '/etc/zabbix/secret.key'
    state: 'absent'
  when: zabbix_agent__deploy_state == 'absent' or
        zabbix_agent__tls_mode != 'psk'

- name: Ensure configuration folder exists
  ansible.builtin.file:
    path: '/etc/zabbix/zabbix_agentd.conf.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: zabbix_agent__deploy_state != 'absent' and
        zabbix_agent__flavor == 'C'

- name: Ensure log folder exists
  ansible.builtin.file:
    path: '/var/log/zabbix-agent'
    state: 'directory'
    owner: '{{ zabbix_agent__user }}'
    group: '{{ zabbix_agent__group }}'
    mode: '0755'
  when: zabbix_agent__deploy_state != 'absent' and
        zabbix_agent__flavor == 'C'

- name: Ensure Go agent configuration folder exists
  ansible.builtin.file:
    path: '/etc/zabbix/zabbix_agent2.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: zabbix_agent__deploy_state != 'absent' and
        zabbix_agent__flavor == 'Go'

# UserParameters and helper scripts [[[1
- name: Ensure Zabbix agent scripts directory exists
  ansible.builtin.file:
    path: '{{ zabbix_agent__scripts_path }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: zabbix_agent__deploy_state != 'absent' and
        zabbix_agent__combined_scripts | length > 0

- name: Manage Zabbix agent helper scripts
  ansible.builtin.copy:
    dest: '{{ zabbix_agent__scripts_path + "/" + item.name }}'
    src: '{{ item.src | d(omit) }}'
    content: '{{ item.content | d(omit) }}'
    owner: '{{ item.owner | d("root") }}'
    group: '{{ item.group | d("root") }}'
    mode: '{{ item.mode | d("0755") }}'
  loop: '{{ zabbix_agent__combined_scripts }}'
  loop_control:
    label: '{{ item.name }}'
  when: zabbix_agent__deploy_state != 'absent' and
        (item.state | d('present') != 'absent')

- name: Remove absent Zabbix agent helper scripts
  ansible.builtin.file:
    path: '{{ zabbix_agent__scripts_path + "/" + item.name }}'
    state: 'absent'
  loop: '{{ zabbix_agent__combined_scripts }}'
  loop_control:
    label: '{{ item.name }}'
  when: (zabbix_agent__deploy_state == 'absent') or
        (item.state | d('present') == 'absent')

- name: Generate Zabbix agent UserParameter configuration
  ansible.builtin.template:
    src: 'etc/zabbix/ansible-userparams.conf.j2'
    dest: '{{ zabbix_agent__user_parameters_conf_path }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    unsafe_writes: '{{ True if (core__unsafe_writes | d(ansible_local.core.unsafe_writes | d()) | bool) else omit }}'
  notify: [ 'Check zabbix-agent and restart', 'Check zabbix-agent2 and restart' ]
  when: zabbix_agent__deploy_state != 'absent' and
        zabbix_agent__combined_user_parameters | length > 0

- name: Remove Zabbix agent UserParameter configuration if unused
  ansible.builtin.file:
    path: '{{ zabbix_agent__user_parameters_conf_path }}'
    state: 'absent'
  notify: [ 'Check zabbix-agent and restart', 'Check zabbix-agent2 and restart' ]
  when: (zabbix_agent__deploy_state == 'absent') or
        (zabbix_agent__combined_user_parameters | length == 0)

# Automatic service monitoring [[[1
- name: Ensure Zabbix Agent 2 plugin configuration directory exists
  ansible.builtin.file:
    path: '/etc/zabbix/zabbix_agent2.d/plugins.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: zabbix_agent__deploy_state != 'absent' and
        zabbix_agent__flavor == 'Go' and
        zabbix_agent__service_templates__combined_plugins | length > 0

- name: Configure Zabbix Agent 2 plugins for detected services
  ansible.builtin.copy:
    dest: '/etc/zabbix/zabbix_agent2.d/plugins.d/{{ item.plugin_name }}'
    content: '{{ item.plugin_content }}'
    owner: 'root'
    group: 'root'
    mode: '0640'
  loop: '{{ zabbix_agent__service_templates__combined_plugins }}'
  loop_control:
    label: '{{ item.name }}'
  no_log: '{{ debops__no_log | d(True) }}'
  notify: [ 'Check zabbix-agent2 and restart' ]
  when: zabbix_agent__deploy_state != 'absent' and
        zabbix_agent__flavor == 'Go'

- name: Remove Zabbix Agent 2 plugin configuration of disabled integrations
  ansible.builtin.file:
    path: '/etc/zabbix/zabbix_agent2.d/plugins.d/{{ item }}'
    state: 'absent'
  loop: '{{ (ansible_local.zabbix_agent.configured_plugins | d([]))
            | difference(zabbix_agent__service_templates__combined_plugins
                          | map(attribute="plugin_name") | list
                          if (zabbix_agent__deploy_state != "absent" and
                              zabbix_agent__flavor == "Go")
                          else []) }}'
  notify: [ 'Check zabbix-agent2 and restart' ]

# Ansible facts [[[1
- name: Make sure that Ansible local fact directory exists
  ansible.builtin.file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: zabbix_agent__deploy_state != 'absent'

- name: Create local facts of Zabbix agent
  ansible.builtin.template:
    src: 'etc/ansible/facts.d/zabbix_agent.fact.j2'
    dest: '/etc/ansible/facts.d/zabbix_agent.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
    unsafe_writes: '{{ True if (core__unsafe_writes | d(ansible_local.core.unsafe_writes | d()) | bool) else omit }}'
  notify: [ 'Refresh host facts' ]
  when: zabbix_agent__deploy_state != 'absent'
  tags: [ 'meta::facts' ]

- name: Prepare cleanup during package removal
  ansible.builtin.import_role:
    name: 'dpkg_cleanup'
  vars:
    dpkg_cleanup__dependent_packages:
      - '{{ zabbix_agent__dpkg_cleanup__dependent_packages }}'
  when: zabbix_agent__deploy_state != 'absent'
  tags: [ 'role::dpkg_cleanup', 'skip::dpkg_cleanup',
          'role::zabbix_agent:dpkg_cleanup' ]

- name: Reload facts if they were modified
  ansible.builtin.meta: 'flush_handlers'

# API self-registration [[[1
- name: Register host in Zabbix Server via API
  ansible.builtin.import_tasks: 'api_register.yml'
  when: zabbix_agent__deploy_state != 'absent' and
        zabbix_agent__api_register | bool
  tags: [ 'role::zabbix_agent:api_register' ]
