# Copyright (C) 2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later
---
# Inventory specification for a DebOps project

# This document is version 0, the paths and file contents are written
# literally.
version: 0

# File and directory definitions, each YAML dictionary key is a file path.
# Paths are relative to the 'inventory/' directory in DebOps project or view.
files:

  # Simple Ansible inventory file in INI format; Ansible does not need a
  # file extension to detect the format
  hosts: |
    # This is an Ansible inventory file in INI format. You can define a list of
    # hosts and groups to be managed by this particular inventory.

    # Hosts listed under [debops_all_hosts] will have common DebOps plays
    # ran against them. It will include services such as iptables, DNS, Postfix,
    # sshd configuration and more.
    #
    # View the list here:
    # https://github.com/debops/debops/blob/master/ansible/playbooks/common.yml
    #
    # You should check Getting Started guide for useful suggestions:
    # https://docs.debops.org/en/master/introduction/getting-started.html

    [webservers]
    web1 ansible_host=web1.example.org
    web2 ansible_host=web2.example.org

    [databases]
    db1 ansible_host=192.0.2.20

    [debops_all_hosts:children]
    webservers
    databases

    [debops_service_nginx:children]
    webservers

    [debops_service_postgresql_server:children]
    databases

    [debops_service_postgresql:children]
    databases

  # Create empty directories for the inventory groups to store per-group
  # inventory variables
  group_vars/webservers/: ''
  group_vars/databases/: ''

  # Create empty directories for hosts to store per-host inventory variables
  host_vars/web1/: ''
  host_vars/web2/: ''
  host_vars/db1/: ''


  # Define default values for DebOps roles on all hosts in the inventory

  group_vars/all/locales.yml: |
    ---
    # Language(s) present on all inventory hosts
    locales__list: [ 'en_US.UTF-8' ]
    locales__system_lang: 'en_US.UTF-8'

  group_vars/all/sshd.yml: |
    ---
    # Networks which may log in over SSH without being blocked by the firewall.
    # Keep this to the range you administer from.
    sshd__whitelist: [ '192.0.2.0/24' ]

  group_vars/all/tzdata.yml: |
    ---
    # Timezone defined on all inventory hosts
    tzdata__timezone: 'Etc/UTC'


  # Define per-group customization for specific DebOps roles

  group_vars/databases/postgresql.yml: |
    ---
    # Use the upstream PostgreSQL APT repository for the client
    postgresql__upstream: True

  group_vars/databases/postgresql_server.yml: |
    ---
    # Use the upstream repository for the server
    postgresql_server__upstream: True

  group_vars/webservers/nginx.yml: |
    ---
    # Server names for the nginx virtual hosts
    nginx__hostname_domains: [ '{{ ansible_domain }}' ]

    # Use the distribution's full nginx package rather than the minimal one.
    nginx_flavor: 'full'
