#!/bin/sh

# Copyright (C) 2014-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# This file is managed by Ansible, all changes will be lost

if tty -s ; then
    if [ -r "${HOME}/.motd" ] ; then
        cat "${HOME}/.motd"
    fi
    echo "Run '<command>' for help, or 'exit' to leave.  Available commands:"
else
    echo "Run '<command>' for help.  Available commands:"
fi

cd "$(dirname "$0")" || exit

for cmd in * ; do
    case "$cmd" in
    help) ;;
    *) [ -f "$cmd" ] && [ -x "$cmd" ] && echo "$cmd" ;;
    esac
done
