#!/bin/sh

# Copyright (C) 2014-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# This file is managed by Ansible, all changes will be lost

set -e

sshkey="${HOME}/.ssh/id_rsa.pub"

if [ ! -r "${sshkey}" ] ; then
    ssh-keygen -f "${HOME}/.ssh/id_rsa" -q -t rsa -N ""
fi

cat "${sshkey}"
