#!/bin/sh

# This file is managed by Ansible, all changes will be lost

set -e

sshkey="${HOME}/.ssh/id_rsa.pub"

if [ ! -r "${sshkey}" ] ; then
    ssh-keygen -f "${HOME}/.ssh/id_rsa" -q -t rsa -N ""
fi

cat "${sshkey}"
