#!/bin/bash

set -o nounset -o pipefail -o errexit

jane notify info "Sending test mail message to root..."
printf "Hello, world!\\n\\nThis is a test message from Jane.\\n" \
    | mail -a "Content-Type: text/plain; charset=utf-8" \
           -s "Test message" "root@$(hostname -f)"

jane notify info "Displaying root mailbox..."
sudo cat /var/mail/root
