---
# Copyright (C) 2025 Marcin Sciborski <marcin@sciborski.com>
# Copyright (C) 2025 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Prepare debops.cloudflared environment
  ansible.builtin.set_fact:
    cloudflared__secret_directories: '{{ lookup("template",
                                         "lookup/cloudflared_env_secret_directories.j2")
                                         | from_yaml }}'
