#!/bin/bash
## @author Copyright (C) 2016 Robin Schneider <ypid@riseup.net>
## @license GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.html>

## Go into the directory where this script is stored.
cd "$( dirname "${BASH_SOURCE[0]}" )" || exit

## Get all files, independently what the current subdirectory is.
cd "$(git rev-parse --show-toplevel)" || exit
(
    git ls-files -z | xargs --null -I '{}' find '{}' -type f -name '*.yml' -print0 | xargs --null egrep --no-filename -e '^\s{4}-\s?role:\s?[^/]+$$' | sed --regexp-extended 's/.*?:\s+//'
    test -r galaxy/requirements-manual.txt && grep --invert-match '^\s*#' galaxy/requirements-manual.txt
) | sort -u
