# {{ ansible_managed }}

{% if postfix_postmap_hash_tables is defined and postfix_postmap_hash_tables %}
HASH_TABLES ={% for name in postfix_postmap_hash_tables %} {{ "%s.db" | format(name) }}{% endfor %}


all: $(HASH_TABLES)

{% if 'aliases' in postfix_postmap_hash_tables %}
aliases.db: aliases.in
	@postalias aliases.in
	@mv aliases.in.db aliases.db

{% endif %}
{% for table in postfix_postmap_hash_tables %}
{% if table != "aliases" %}
{{ table }}.db: {{ table }}.in
	@postmap {{ table }}.in
	@mv {{ table }}.in.db {{ table }}.db

{% endif %}
{% endfor %}
{% endif %}


