#!/bin/bash

# Copyright (C) 2018-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2018-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

if ! dpkg --get-selections | diff - /var/backups/dpkg-selections.log > /dev/null 2>&1 ; then
    printf "  %s\\n" "Writing dpkg selections to /var/backups/dpkg-selections.log..."
    dpkg --get-selections > /var/backups/dpkg-selections.log
fi
