# override environment variables
ENV['PROJECT_DIR'] = '../../..'
ENV['CI_PROJECT_DIR'] = '../../..'

# include master Vagrantfile
master_vagrantfile = File.expand_path('../../../Vagrantfile')
load master_vagrantfile if File.exists?(master_vagrantfile)
