# This file is managed remotely, all changes will be lost

PKI_BASE_PATH			= {{ pki_base_path      | default('/etc/pki') }}

PKI_DEFAULT_REALM		= {{ pki_default_realm | default('host') }}
PKI_REALMS			= $(filter-out $(DEFAULT_REALM)/,$(sort $(dir $(shell find */ -maxdepth 1 -name Makefile))))

DEFAULT_REALM			= system

SNAPSHOT_PATH			= {{ pki_snapshot_path  | default('/var/backups') }}
SNAPSHOT_FILE			= {{ pki_snapshot_file  | default('pki-snapshot-' + ansible_fqdn + '.tar') }}
SNAPSHOT_OWNER			= {{ pki_snapshot_owner | default('root') }}
SNAPSHOT_GROUP			= {{ pki_snapshot_group | default('root') }}
SNAPSHOT_MODE			= 0640
SNAPSHOT_DEST			= $(SNAPSHOT_PATH)/$(SNAPSHOT_FILE)

.PHONY: $(PKI_REALMS) $(DEFAULT_REALM) $(SNAPSHOT_DEST) restore

all: all-realms

all-realms: $(PKI_REALMS) $(DEFAULT_REALM)

regenerate-dhparams:
	@for realm in $$(find . -maxdepth 1 -type d -not -name .) ; do \
		cd $$realm ; make regenerate-dhparams ; cd - > /dev/null ; \
	done

snapshot: $(SNAPSHOT_DEST)

restore:
	@test -n "$(SNAPSHOT_DEST)" && test -e $(SNAPSHOT_DEST) && tar xvf $(SNAPSHOT_DEST)

$(DEFAULT_REALM): $(PKI_DEFAULT_REALM)
	@test -n "$<" && test -e "$<" && ( \
		test -n "$@" && test -L $@ && test "$(shell readlink -f $@)" = "$(shell readlink -f "$<")" || ( \
			rm -f $@ && ln -sf $< $@ && \
			echo "$@ -> $<" \
		) \
	) || ( \
		test -n "$@" && test -L $@ && rm -f $@ || true \
	)

$(PKI_REALMS):
	@test -n "$@" && cd $@ && make --no-print-directory all

$(SNAPSHOT_DEST):
	@test -n "$(PKI_REALMS)" && test -n "$@" && test -e $@ && \
		tar --exclude '$(DEFAULT_REALM)' --exclude '*/dhparams' --exclude '*/dhparam.pem' -uvpf $@ --one-file-system $(PKI_REALMS) && \
		tar --exclude '$(DEFAULT_REALM)' --exclude '*/dhparams' --exclude '*/dhparam.pem' -dpf $@ --one-file-system $(PKI_REALMS) || ( \
		touch $@.tmp && chmod $(SNAPSHOT_MODE) $@.tmp && chown $(SNAPSHOT_OWNER).$(SNAPSHOT_GROUP) $@.tmp && \
		tar --exclude '$(DEFAULT_REALM)' -cvpf $@.tmp --one-file-system $(PKI_REALMS) && mv $@.tmp $@ \
	)

