---
# Copyright (C) 2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Install and configure D-I Netboot Assistant
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_service_netboot_assistant' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import netboot_assistant role
      ansible.builtin.import_role:
        name: 'debops.debops.netboot_assistant'
      tags: [ 'role::netboot_assistant', 'skip::netboot_assistant' ]
