---
# Copyright (C) 2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Update APT cache on hosts
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_hosts', 'debops_all_services', 'debops_service_apt' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import apt role
      ansible.builtin.import_role:
        name: 'debops.debops.apt'
        tasks_from: 'main_update.yml'
      tags: [ 'role::apt', 'skip::apt' ]
