#!/bin/sh

# shellcheck disable=SC2034
BLACK='\033[49;30m'
BLACKB='\033[49;90m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[94;49m'
MAGENTA='\033[0;35m'
CYAN='\033[36;49m'
WHITE='\033[0;37m'
BOLD='\033[1m'
RESET='\033[0m'

if [ -d "/etc/ansible/facts.d" ] ; then
    printf "${BLACKB}%70s${RESET}\\n" | tr ' ' -
    # shellcheck disable=SC2059
    printf "    ${CYAN}This system is managed by ${BOLD}Ansible${RESET}${CYAN}, manual changes will be lost${RESET}\\n"
    printf "${BLACKB}%70s${RESET}\\n" | tr ' ' -
fi
