---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2026 Patryk Ściborek <patryk@sciborek.com>
# Copyright (C) 2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

collections: [ 'debops.debops', 'community.general', 'community.postgresql' ]

dependencies: []

galaxy_info:

  author: 'DebOps'
  description: 'Manage Zabbix server, database schema and frontend'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.10.0'

  platforms:

    - name: 'Debian'
      versions:
        - 'bullseye'
        - 'bookworm'
        - 'trixie'

  galaxy_tags:
    - zabbix
    - monitoring
    - postgresql
    - nginx
    - php
