#!/bin/sh

# Copyright (C) 2015 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Detect installed operating system release

if [ -r /etc/os-release ] ; then
  # shellcheck disable=SC1091
  . /etc/os-release

  echo "${PRETTY_NAME}"
fi

