#!/bin/bash

# Return Redis password

set -eu -o pipefail

redis_conf="${1:-/etc/redis/redis.conf}"

if [ -r "${redis_conf}" ] ; then
    grep -E '^requirepass' "${redis_conf}" | awk '{print $2}' | sed -e 's/^"//' -e 's/"$//'
fi
