#!/bin/bash
## @author Copyright (C) 2016 Robin Schneider <ypid@riseup.net>
## @license AGPL-3.0 <https://www.gnu.org/licenses/agpl-3.0.html>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU Affero General Public License as
## published by the Free Software Foundation, version 3 of the
## License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program.  If not, see <https://www.gnu.org/licenses/>.

## Go into the directory where this script is stored.
cd "$( dirname "${BASH_SOURCE[0]}" )" || exit

## Get all files, independently what the current subdirectory is.
cd "$(git rev-parse --show-toplevel)" || exit

git ls-files -z | xargs --null -I '{}' find '{}' -type f -name '*.yml' -print0 | xargs --null egrep --no-filename -e '^\s*-\s?role:\s?[^/]+$$' | sort -u | sed --regexp-extended 's/.*?:\s+//'
