#!/bin/bash

## HERE BE DRAGONS! This pre-commit hook might eat your changes. Testing required.

## Stash upstaged changes.
git stash -q --keep-index

## Git does not like that in this context (it will show deleted files):
# cd docs && git status

make --makefile docs/_tests/Makefile check
RESULT=$?

## Revert upstaged changes which might be done to the working copy.
git checkout-index --force --all

## Apply upstaged changes from the stash to the working copy.
git stash pop -q

[ $RESULT -ne 0 ] && exit 1
exit 0
