---
# Copyright (C) 2017-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2017-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage Avahi service
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services', 'debops_service_avahi' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import avahi role
      ansible.builtin.import_role:
        name: 'debops.debops.avahi'
      tags: [ 'role::avahi', 'skip::avahi' ]
