---
# Copyright (C) 2022 David Härdeman <david@hardeman.nu>
# Copyright (C) 2022-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage BIND servers
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services', 'debops_service_bind' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import bind role
      ansible.builtin.import_role:
        name: 'debops.debops.bind'
      tags: [ 'role::bind', 'skip::bind' ]
