---
# Copyright (C) 2019-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2019-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage Docker Registry
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services', 'debops_service_docker_registry' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import docker_registry role
      ansible.builtin.import_role:
        name: 'debops.debops.docker_registry'
      tags: [ 'role::docker_registry', 'skip::docker_registry' ]
