---
# Copyright (C) 2014-2016 Nick Janetakis <nick.janetakis@gmail.com>
# Copyright (C) 2014-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2016      Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# Copyright (C) 2014-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage Elasticsearch cluster
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services',
           'debops_service_elasticsearch',
           'debops_service_elasticsearch_master',
           'debops_service_elasticsearch_data',
           'debops_service_elasticsearch_ingest',
           'debops_service_elasticsearch_lb' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  pre_tasks:

    - name: Prepare elasticsearch environment
      ansible.builtin.import_role:
        name: 'debops.debops.elasticsearch'
        tasks_from: 'main_env'
      tags: [ 'role::elasticsearch', 'role::elasticsearch:env', 'role::elasticsearch:config' ]

  tasks:

    - name: Import elasticsearch role
      ansible.builtin.import_role:
        name: 'debops.debops.elasticsearch'
      tags: [ 'role::elasticsearch', 'skip::elasticsearch' ]
