---
# Copyright (C) 2018-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2018-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure Icinga service
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services', 'debops_service_icinga' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  pre_tasks:

    - name: Prepare icinga environment
      ansible.builtin.import_role:
        name: 'debops.debops.icinga'
        tasks_from: 'main_env'
      tags: [ 'role::icinga', 'role::icinga:env' ]

  tasks:

    - name: Import icinga role
      ansible.builtin.import_role:
        name: 'debops.debops.icinga'
      tags: [ 'role::icinga', 'skip::icinga' ]
