---
# Copyright (C) 2022-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2022-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Manage Advanced Package Manager
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services', 'debops_service_keepalived' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import keepalived role
      ansible.builtin.import_role:
        name: 'debops.debops.keepalived'
      tags: [ 'role::keepalived', 'skip::keepalived' ]
