---
# Copyright (C) 2015-2018 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2018-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2018-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage kernel modules
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services', 'debops_service_kmod' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import kmod role
      ansible.builtin.import_role:
        name: 'debops.debops.kmod'
      tags: [ 'role::kmod', 'skip::kmod' ]
