---
# Copyright (C) 2019-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2019-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage MinIO Client (mcli) installation
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services', 'debops_service_mcli' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  pre_tasks:

    - name: Prepare mcli environment
      ansible.builtin.import_role:
        name: 'debops.debops.mcli'
        tasks_from: 'main_env'
      tags: [ 'role::mcli', 'role::mcli:env' ]

  tasks:

    - name: Import mcli role
      ansible.builtin.import_role:
        name: 'debops.debops.mcli'
      tags: [ 'role::mcli', 'skip::mcli' ]
