---
# Copyright (C) 2018-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2018-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage local device and bind mounts
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_hosts', 'debops_all_services', 'debops_service_mount' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import mount role
      ansible.builtin.import_role:
        name: 'debops.debops.mount'
      tags: [ 'role::mount', 'skip::mount' ]
