---
# Copyright (C) 2014-2026 Maciej Delmanowski <drybjed@drybjed.net>
# Copyright (C) 2015-2017 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2014-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage nginx webserver
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services', 'debops_service_nginx' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import nginx role
      ansible.builtin.import_role:
        name: 'debops.debops.nginx'
      tags: [ 'role::nginx', 'skip::nginx' ]
