---
# Copyright (C) 2015-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015      Hartmut Goebel <h.goebel@crazy-compilers.com>
# Copyright (C) 2015-2019 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2015-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage NextCloud/ownCloud instances
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services', 'debops_service_owncloud' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import owncloud role
      ansible.builtin.import_role:
        name: 'debops.debops.owncloud'
      tags: [ 'role::owncloud', 'skip::owncloud' ]
