---
# Copyright (C) 2025-2026 Maciej Delmanowski <drybjed@drybjed.net>
# Copyright (C) 2025-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Manage pgBadger service
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services', 'debops_service_pgbadger' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import pgbadger role
      ansible.builtin.import_role:
        name: 'debops.debops.pgbadger'
      tags: [ 'role::pgbadger', 'skip::pgbadger' ]
