---
# Copyright (C) 2017-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2017-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure sysfs options
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services', 'debops_service_sysfs' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  pre_tasks:

    - name: Prepare sysfs environment
      ansible.builtin.import_role:
        name: 'debops.debops.sysfs'
        tasks_from: 'main_env'
      tags: [ 'role::sysfs', 'role::sysfs:env' ]

  tasks:

    - name: Import sysfs role
      ansible.builtin.import_role:
        name: 'debops.debops.sysfs'
      tags: [ 'role::sysfs', 'skip::sysfs' ]
