---
# Copyright (C) 2018-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2018-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure UNIX system groups
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_hosts', 'debops_all_services', 'debops_service_system_groups' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import system_groups role
      ansible.builtin.import_role:
        name: 'debops.debops.system_groups'
      tags: [ 'role::system_groups', 'skip::system_groups' ]
