---
# Copyright (C) 2015-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2016-2017 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2015-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure Tinc VPN
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_services', 'debops_service_tinc' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  pre_tasks:

    - name: Prepare tinc environment
      ansible.builtin.import_role:
        name: 'tinc'
        tasks_from: 'main_env'
      tags: [ 'role::tinc', 'role::tinc:env' ]

  tasks:

    - name: Import tinc role
      ansible.builtin.import_role:
        name: 'debops.debops.tinc'
      tags: [ 'role::tinc', 'skip::tinc' ]
