---
# Copyright (C) 2019-2026 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2019-2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Configure yadm, Yet Another Dotfiles Manager
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_hosts', 'debops_all_services', 'debops_service_yadm' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Import yadm role
      ansible.builtin.import_role:
        name: 'debops.debops.yadm'
      tags: [ 'role::yadm', 'skip::yadm' ]
